-- The account database, translated from services/accounts.py (SQLite).
--
-- Derived from, in accounts.py:
--   SCHEMA                          every CREATE TABLE and CREATE INDEX
--   _MIGRATIONS                     the ADD COLUMN list (member, handle, friend,
--                                   group_member), folded into the tables below
--   _migrate_handle_profile         handle_profile keyed on handle_id
--   _migrate_handle_content_slots   handle_content keyed on (handle, code, slot)
--   the trim-ffxi-slots command     handle_content_trimmed (now in the FFXI
--                                   plugin, which created it lazily)
--   character_names()               content_character, which the FFXI bridge's
--                                   tools/ffxi_names.py creates today; the plan
--                                   moves it into this schema (Phase 2 step A)
--
-- Left out on purpose: handle_profile_by_member and handle_content_pre_slots.
-- They are the copies the two rebuild functions keep of pre-rebuild rows, and a
-- database created from this file never had those rows. The import tool reads
-- them from the old accounts.db if an operator needs them.
--
-- Types. Ids are BIGINT identities (BY DEFAULT, so an import can keep the ids
-- it copies; it must setval() the sequences afterwards). Every column SQLite
-- declared INTEGER that holds an id, a guid or a client value is BIGINT, since
-- a SQLite INTEGER is 64-bit. Small codes, flags and counts are INTEGER; the
-- flags stay integers because the code compares them with = 0 / = 1.
-- Timestamps stay TEXT: accounts.py writes ISO-8601 UTC strings
-- ("2026-09-27T12:00:00Z") and compares them as strings. login_fail.at is unix
-- seconds as a float (REAL in SQLite). BLOB is BYTEA.
--
-- Foreign keys. SQLite only enforced them on the one connection that ran
-- PRAGMA foreign_keys = ON, so accounts.py deletes children explicitly and does
-- not rely on the cascades (see delete_polid). Postgres enforces them always.
-- The declared actions are kept as they were.
--
-- Case. SQLite compared these columns case-sensitively, as Postgres does; the
-- lookups that fold case (COLLATE NOCASE in accounts.py) become lower(x) =
-- lower(y), and the lower() indexes at the end serve them.

CREATE TABLE polid (
    polid       TEXT PRIMARY KEY,
    pw_hash     TEXT NOT NULL,
    pw_salt     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    area_kbn    TEXT NOT NULL DEFAULT '00',
    login_pf    TEXT NOT NULL DEFAULT '01',
    property    TEXT NOT NULL DEFAULT '00',
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE member (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polid           TEXT NOT NULL REFERENCES polid(polid) ON DELETE CASCADE,
    member_no       INTEGER NOT NULL,
    login_name      TEXT NOT NULL UNIQUE,
    pw_hash         TEXT NOT NULL,
    pw_salt         TEXT NOT NULL,
    access_level    INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TEXT NOT NULL,
    -- added by _MIGRATIONS["member"]
    mail_address    TEXT,
    mail_pw_hash    TEXT,
    mail_pw_salt    TEXT,
    mail_pw_plain   TEXT,
    last_login_at   TEXT,
    prev_login_at   TEXT,
    last_logout_at  TEXT,
    login_token     TEXT,
    token_arm_until TEXT,
    ext_mail        INTEGER NOT NULL DEFAULT 0,
    login_pw_sealed TEXT,
    UNIQUE (polid, member_no)
);

CREATE TABLE handle (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    handle_name TEXT NOT NULL UNIQUE,
    is_primary  INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT NOT NULL,
    -- added by _MIGRATIONS["handle"]
    client_guid BIGINT
);

CREATE TABLE login_alias (
    nick       TEXT PRIMARY KEY,
    member_id  BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    note       TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE deleted_handle (
    member_id   BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    handle_name TEXT NOT NULL,
    deleted_at  TEXT NOT NULL,
    PRIMARY KEY (member_id, handle_name)
);

-- The identity sequence is named explicitly: its default name would be
-- content_id_seq, which is the Content ID counter table below.
CREATE TABLE content (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY
                  (SEQUENCE NAME content_row_id_seq) PRIMARY KEY,
    member_id     BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    content_code  INTEGER NOT NULL,
    content_no    TEXT,
    status        TEXT NOT NULL DEFAULT 'active',
    registered_at TEXT NOT NULL,
    UNIQUE (member_id, content_code)
);

CREATE TABLE handle_content (
    handle_id    BIGINT NOT NULL REFERENCES handle(id) ON DELETE CASCADE,
    content_code INTEGER NOT NULL,
    slot         INTEGER NOT NULL DEFAULT 0,
    content_id   TEXT,
    status       TEXT NOT NULL DEFAULT 'active',
    linked_at    TEXT NOT NULL,
    PRIMARY KEY (handle_id, content_code, slot)
);

-- A Content ID belongs to exactly one handle; NULL (not yet minted) is exempt.
CREATE UNIQUE INDEX handle_content_id_unique
    ON handle_content (content_id) WHERE content_id IS NOT NULL;

CREATE TABLE content_id_seq (
    id      INTEGER PRIMARY KEY CHECK (id = 1),
    next_id BIGINT NOT NULL
);

CREATE TABLE friend (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle_id    BIGINT NOT NULL REFERENCES handle(id) ON DELETE CASCADE,
    peer_handle  BIGINT REFERENCES handle(id) ON DELETE SET NULL,
    peer_name    TEXT NOT NULL,
    peer_guid    BIGINT NOT NULL DEFAULT 0,
    kind         INTEGER NOT NULL DEFAULT 2048,
    status       TEXT NOT NULL DEFAULT 'active',
    comment      TEXT,
    label        TEXT,
    ignore_low   INTEGER,
    ignore_flag  INTEGER,
    created_at   TEXT NOT NULL,
    -- added by _MIGRATIONS["friend"]
    client_ref   BYTEA,
    wire_ref     BYTEA,
    UNIQUE (handle_id, peer_name)
);

CREATE TABLE group_member (
    group_id      BIGINT NOT NULL REFERENCES friend(id) ON DELETE CASCADE,
    member_handle BIGINT REFERENCES handle(id) ON DELETE SET NULL,
    member_name   TEXT NOT NULL,
    member_guid   BIGINT NOT NULL DEFAULT 0,
    class         INTEGER NOT NULL DEFAULT 3,
    pending       INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT NOT NULL,
    PRIMARY KEY (group_id, member_name)
);

CREATE TABLE session (
    token      TEXT PRIMARY KEY,
    member_id  BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    nick       TEXT,
    peer_ip    TEXT,
    iv         TEXT,
    lobby_port INTEGER,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);

CREATE TABLE handle_profile (
    handle_id  BIGINT NOT NULL REFERENCES handle(id) ON DELETE CASCADE,
    field_id   INTEGER NOT NULL,
    val_int    BIGINT,
    val_text   TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (handle_id, field_id)
);

CREATE TABLE profile (
    polid           TEXT PRIMARY KEY REFERENCES polid(polid) ON DELETE CASCADE,
    kanji_family    TEXT,
    kanji_first     TEXT,
    katakana_family TEXT,
    katakana_first  TEXT,
    zip_main        TEXT,
    zip_sub         TEXT,
    address_0       TEXT,
    address_1       TEXT,
    address_2       TEXT,
    phone_0         TEXT,
    phone_1         TEXT,
    phone_2         TEXT,
    country         TEXT,
    updated_at      TEXT NOT NULL
);

CREATE TABLE regcode (
    code        TEXT PRIMARY KEY,
    contents    TEXT NOT NULL DEFAULT '1',
    note        TEXT,
    created_at  TEXT NOT NULL,
    redeemed_at TEXT,
    redeemed_by TEXT REFERENCES polid(polid)
);

CREATE TABLE mail (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box         TEXT NOT NULL,
    member_id   BIGINT REFERENCES member(id) ON DELETE CASCADE,
    uidl        TEXT NOT NULL,
    sender      TEXT,
    subject     TEXT,
    raw         BYTEA NOT NULL,
    received_at TEXT NOT NULL,
    deleted_at  TEXT,
    UNIQUE (box, uidl)
);

CREATE TABLE admin_cred (
    id         INTEGER PRIMARY KEY CHECK (id = 1),
    username   TEXT NOT NULL,
    pw_hash    TEXT NOT NULL,
    pw_salt    TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE login_token_client (
    member_id  BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    client_sig TEXT NOT NULL,
    token      TEXT NOT NULL,
    first_seen TEXT NOT NULL,
    last_seen  TEXT NOT NULL,
    PRIMARY KEY (member_id, client_sig)
);

CREATE TABLE ext_mail_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT REFERENCES member(id) ON DELETE CASCADE,
    direction  TEXT NOT NULL,          -- 'out' | 'in'
    peer_addr  TEXT,
    at         TEXT NOT NULL,
    ok         INTEGER NOT NULL,
    detail     TEXT
);

CREATE TABLE login_digest_client (
    client_sig  TEXT PRIMARY KEY,
    member_id   BIGINT,
    proven_at   TEXT NOT NULL
);

-- No key and no foreign key, as in SQLite: one row per refused password.
CREATE TABLE login_fail (
    member_id   BIGINT NOT NULL,
    at          DOUBLE PRECISION NOT NULL,
    peer_ip     TEXT,
    client_sig  TEXT
);
CREATE INDEX idx_login_fail ON login_fail (member_id, at);

CREATE TABLE list_stamp (
    member_id   BIGINT NOT NULL REFERENCES member(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    stamp       BIGINT NOT NULL,
    PRIMARY KEY (member_id, kind)
);

-- The rows the FFXI trim-ffxi-slots command deactivated, so --restore can put
-- them back. That command used to create it lazily; the schema owns it now. No
-- keys, as in the command's own CREATE.
CREATE TABLE handle_content_trimmed (
    handle_id    BIGINT NOT NULL,
    content_code INTEGER NOT NULL,
    slot         INTEGER NOT NULL,
    content_id   TEXT,
    prev_status  TEXT,
    trimmed_at   TEXT
);

-- The game character's own name per Content ID (FFXI today). content_id is
-- TEXT in two widths, as in handle_content; readers match it numerically.
CREATE TABLE content_character (
    content_id     TEXT NOT NULL,
    content_code   INTEGER NOT NULL DEFAULT 1,
    world_charid   BIGINT,
    character_name TEXT NOT NULL,
    world_name     TEXT,
    first_seen     TEXT NOT NULL,
    last_seen      TEXT NOT NULL,
    PRIMARY KEY (content_id, content_code)
);
CREATE INDEX content_character_by_name ON content_character (character_name);

CREATE INDEX idx_member_polid   ON member (polid);
CREATE INDEX idx_content_member ON content (member_id);
CREATE INDEX idx_session_member ON session (member_id);
CREATE INDEX idx_mail_box       ON mail (box, deleted_at);
CREATE INDEX idx_ext_mail_log   ON ext_mail_log (member_id, direction, at);

-- For the case-folding lookups (COLLATE NOCASE in accounts.py): a handle or
-- friend named in the wrong case, a registration code typed in lower case, a
-- mailbox found by address.
CREATE INDEX idx_handle_name_lower   ON handle (lower(handle_name));
CREATE INDEX idx_friend_peer_lower   ON friend (handle_id, lower(peer_name));
CREATE INDEX idx_regcode_code_lower  ON regcode (lower(code));
CREATE INDEX idx_member_mail_lower   ON member (lower(mail_address));
