-- The two small stores that had SQLite files of their own, and what the
-- account code needs on top of 0001 now that it runs on PostgreSQL.
--
-- admin_*    services/adminusers.py, formerly /data/admin.db: moderator
--            logins, the admin panel's audit log, who made each registration
--            code, panel settings, Web Push subscriptions and the GM-call
--            alert bookkeeping. The tables were `moderator`, `audit`,
--            `code_origin`, `setting`, `push_sub` and `alerted`; they carry the
--            admin_ prefix here because they now share one database with
--            everything else.
-- discord_*  services/discordlink.py, formerly /data/discord_links.db: the
--            PlayOnline <-> Discord links, the one-time link codes and the
--            bridge's bookkeeping. Formerly `link`, `code`, `notified`,
--            `reply`, `sent` and `meta`.
--
-- Types follow 0001: ids BIGINT, SQLite REAL (unix seconds) DOUBLE PRECISION,
-- flags INTEGER. Neither store had foreign keys into the account tables and
-- none are added: a link or an audit row outliving a deleted member is what
-- both did before.
--
-- Case. adminusers declared `moderator.username` and `code_origin.code`
-- COLLATE NOCASE, so lookups, uniqueness and ordering on them ignored case.
-- Here they are unique on lower(...) and the code compares lower(...).

CREATE TABLE admin_moderator (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    pw_hash       TEXT NOT NULL,
    pw_salt       TEXT NOT NULL,
    perms         TEXT NOT NULL DEFAULT '',
    code_limit    INTEGER,              -- codes per rolling 24 h; NULL = no limit
    disabled      INTEGER NOT NULL DEFAULT 0,
    created_at    DOUBLE PRECISION NOT NULL,
    created_by    TEXT,
    pw_changed_at DOUBLE PRECISION NOT NULL,  -- part of a session's credential tie
    titles        TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX admin_moderator_username ON admin_moderator (lower(username));

CREATE TABLE admin_audit (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at      DOUBLE PRECISION NOT NULL,
    actor   TEXT NOT NULL,
    role    TEXT NOT NULL,
    action  TEXT NOT NULL,
    target  TEXT,
    detail  TEXT,
    ok      INTEGER NOT NULL,
    addr    TEXT
);
CREATE INDEX admin_audit_at ON admin_audit (at);
CREATE INDEX admin_audit_actor ON admin_audit (lower(actor));
CREATE INDEX admin_audit_target ON admin_audit (lower(target));

-- `by` is a reserved word in PostgreSQL; the column keeps its name, quoted.
CREATE TABLE admin_code_origin (
    code       TEXT NOT NULL,
    "by"       TEXT NOT NULL,
    role       TEXT NOT NULL,
    at         DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION,
    expired    INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX admin_code_origin_code ON admin_code_origin (lower(code));
CREATE INDEX admin_code_origin_by ON admin_code_origin (lower("by"), at);

CREATE TABLE admin_setting (
    key   TEXT PRIMARY KEY,
    value TEXT
);

-- One row per browser that asked for GM-call alerts (Web Push).
CREATE TABLE admin_push_sub (
    endpoint   TEXT PRIMARY KEY,
    p256dh     TEXT NOT NULL,
    auth       TEXT NOT NULL,
    username   TEXT NOT NULL,
    role       TEXT NOT NULL,
    uid        BIGINT,
    origin     TEXT,
    ua         TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    last_ok    DOUBLE PRECISION,
    last_error TEXT
);

-- GM-call tickets already announced, so a restart never alerts twice.
CREATE TABLE admin_alerted (
    ticket  TEXT PRIMARY KEY,
    at      DOUBLE PRECISION NOT NULL,
    result  TEXT
);

CREATE TABLE discord_link (
    discord_id   TEXT PRIMARY KEY,
    member_id    BIGINT NOT NULL UNIQUE,
    discord_name TEXT,
    linked_at    DOUBLE PRECISION NOT NULL,
    notify       INTEGER NOT NULL DEFAULT 1,
    dm_channel   TEXT
);

CREATE TABLE discord_code (
    code         TEXT PRIMARY KEY,
    discord_id   TEXT NOT NULL,
    discord_name TEXT,
    created_at   DOUBLE PRECISION NOT NULL
);

-- A message file the bridge has finished with (DM'd, or decided not to).
CREATE TABLE discord_notified (
    name TEXT PRIMARY KEY,
    at   DOUBLE PRECISION NOT NULL
);

-- What a Reply button answers: from which of the member's handles, to whom.
-- peer_guid stays TEXT: a guid is a u64, and BIGINT is signed.
CREATE TABLE discord_reply (
    id         TEXT PRIMARY KEY,
    member_id  BIGINT NOT NULL,
    handle_id  BIGINT NOT NULL,
    peer_guid  TEXT NOT NULL,
    peer_name  TEXT,
    subject    TEXT,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE discord_sent (
    member_id BIGINT NOT NULL,
    at        DOUBLE PRECISION NOT NULL
);
CREATE INDEX discord_sent_member ON discord_sent (member_id, at);

CREATE TABLE discord_meta (
    k TEXT PRIMARY KEY,
    v TEXT
);

-- A group's members in the order they were first added. accounts.py listed
-- them ORDER BY rowid, SQLite's implicit insertion counter, which an upsert
-- keeps; PostgreSQL has no such column, so this is it. Existing rows are
-- numbered in the order the table holds them. An import from accounts.db
-- inserts in rowid order to keep that order.
ALTER TABLE group_member
    ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX idx_group_member_seq ON group_member (group_id, seq);

-- SQLite's CAST(x AS INTEGER): the leading integer of the text, 0 when there
-- is none, NULL for NULL. PostgreSQL's own cast raises on anything that is not
-- a clean integer, and content.content_no is operator-typed text that need not
-- be one. Used where accounts.py compares a Content ID numerically.
CREATE FUNCTION text_int(t TEXT) RETURNS BIGINT
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    RETURN CASE WHEN t IS NULL THEN NULL
                ELSE COALESCE(substring(t FROM '^\s*([+-]?[0-9]{1,18})')::BIGINT, 0)
           END;

CREATE INDEX idx_handle_content_id_int ON handle_content (text_int(content_id));
