"""The OpenLobby core server: PlayOnline login, lobby, world and mail responders.

The code lives in the `core` package, one module per concern (see
core/__init__.py for the layout). This module is the entry point the
containers run (`python responders.py <mode[,mode...]>`) and a compatibility
facade: `import responders as R` still resolves every name, reading or
writing, to the module that owns it, so tools and tests written against the
old single-file layout keep working while they are moved over.

    modes: patch directory authcap authserv lobby world mail all
"""
import sys
import types

# ONE COPY OF THIS MODULE. The containers run `python responders.py`, so the
# running copy is `__main__`, and a late `import responders` (a title plugin's
# helper, polbridge) would otherwise load a second copy whose module-level
# code re-runs, including the title binding in core.boot.
if __name__ == "__main__":
    sys.modules.setdefault("responders", sys.modules[__name__])

from core import (  # noqa: E402,F401
    deps,
    patch,
    redirect,
    logingate,
    directory,
    authcap,
    authnode,
    pfc,
    presence,
    gamenotice,
    chatsession,
    roomregistry,
    friendroster,
    pushchannel,
    pushrecord,
    memberstatus,
    titlezone,
    pushspool,
    ircband,
    authserv,
    authresume,
    framing,
    lobbysession,
    paylen,
    fetchpath,
    lobbysearch,
    friendput,
    lobbybind,
    lobbyreply,
    handlelists,
    friendgroups,
    ffxifields,
    characters,
    friendlist,
    lobbymail,
    contentprofiles,
    profilerecord,
    lobbyrooms,
    resourcestore,
    pacing,
    lobbycapture,
    tlsrelay,
    portalauth,
    portalpages,
    lobbyserver,
    worldserver,
    serving,
    mailserver,
    posture,
    boot,
    main,
)
from core.main import main  # noqa: E402

# Which core module owns each top-level name of the old responders.py.
_OWNERS = {
    'A64': 'authnode',
    'BUILDS_PATH': 'portalpages',
    'CLIENT_BUILDS_PATH': 'pacing',
    'CONFIG_PATH': 'deps',
    'ChatSession': 'chatsession',
    'ERAS_PATH': 'portalpages',
    'FRIEND_ENTRY': 'profilerecord',
    'FRIEND_FRIEND': 'profilerecord',
    'FRIEND_GROUP': 'profilerecord',
    'FRIEND_SELF': 'profilerecord',
    'K0_IV': 'authnode',
    'LOG_DIR': 'deps',
    'MAIL_COUNT_BLOCK': 'lobbyreply',
    'MAIL_DOMAIN': 'mailserver',
    'MAIL_KIND_FRIEND_ACCEPTED': 'lobbymail',
    'MAIL_KIND_FRIEND_REQUEST': 'lobbymail',
    'MAIL_KIND_GROUP_INVITE': 'lobbymail',
    'MAIL_KIND_GROUP_REGISTERED': 'lobbymail',
    'MAIL_KIND_MESSAGE': 'lobbymail',
    'MAIL_RECORD': 'lobbyreply',
    'NICK_CLIENT_SIG_LEN': 'authserv',
    'NoPad': 'authnode',
    'POLP_CMD8': 'patch',
    'PRESENCE': 'presence',
    'PresenceRegistry': 'presence',
    'REJECT_BAD_PASSWORD': 'logingate',
    'REJECT_BUSY': 'logingate',
    'REJECT_LOCKED': 'logingate',
    'REJECT_UNKNOWN_ERROR': 'logingate',
    'REJECT_UNKNOWN_ID': 'logingate',
    'REJECT_VERSION': 'logingate',
    'REPORT_DIR': 'mailserver',
    'RESOURCE_DIR': 'resourcestore',
    'RESOURCE_INIT': 'resourcestore',
    'ROOMS': 'roomregistry',
    'RoomRegistry': 'roomregistry',
    'SESSION_RECORD_LEN': 'lobbysession',
    'TOKEN0': 'authnode',
    'TOKEN_ALPHABET': 'deps',
    '_ACCT_MAIL_MAX': 'lobbyreply',
    '_ACCT_MAIL_OFF': 'lobbyreply',
    '_ACCT_SLOT_OFFSETS': 'lobbyreply',
    '_ACCT_STATUS': 'deps',
    '_ACCT_STR_MAX': 'lobbyreply',
    '_ACCT_STR_OFFSETS': 'lobbyreply',
    '_ACTIVE_HANDLE_OFF': 'profilerecord',
    '_B64': 'logingate',
    '_BIND_FLIPS': 'lobbybind',
    '_BIND_LAST': 'lobbybind',
    '_BIND_NOTE_LOCK': 'lobbybind',
    '_BIND_PROVEN': 'lobbybind',
    '_BIND_PROVEN_KEEP': 'lobbybind',
    '_BROWSE_ZONE': 'lobbyrooms',
    '_BUILD_ID': 'portalpages',
    '_CAP_KEEP': 'deps',
    '_CAP_LOCK': 'deps',
    '_CAP_SEEN': 'deps',
    '_CHAR_PER_HANDLE': 'handlelists',
    '_CHAR_SLOTS': 'handlelists',
    '_CHR_PUT_BLOCKS_OFF': 'friendgroups',
    '_CHR_PUT_BODY': 'friendgroups',
    '_CHR_PUT_BOUND': 'friendgroups',
    '_CHR_PUT_CKSUM_OFF': 'friendgroups',
    '_CHR_PUT_PAYLOAD_OFF': 'friendgroups',
    '_CHR_PUT_SLOTS': 'friendgroups',
    '_CHR_PUT_UNBOUND': 'friendgroups',
    '_COMMENT_CTL': 'lobbysession',
    '_COMMENT_CTL_FILE': 'lobbysession',
    '_COMMENT_FIELD': 'profilerecord',
    '_COMMENT_MAX': 'profilerecord',
    '_COMMENT_OFF': 'profilerecord',
    '_CONNS': 'serving',
    '_CONST_48': 'deps',
    '_CONST_END': 'deps',
    '_CONTENT_PHEAD': 'contentprofiles',
    '_CONTENT_RECORD': 'lobbymail',
    '_CONTENT_SCHEMA': 'lobbymail',
    '_CONTENT_SCHEMAS': 'contentprofiles',
    '_CREATED_ROOMS': 'lobbyrooms',
    '_CREATED_ROOMS_LOCK': 'lobbyrooms',
    '_DOC_NAME': 'contentprofiles',
    '_DOC_RANK': 'contentprofiles',
    '_DOC_RANKPOINT': 'contentprofiles',
    '_ERA_CACHE': 'portalpages',
    '_ERA_LAST': 'portalpages',
    '_FETCH_PATHLEN': 'paylen',
    '_FETCH_PATHLEN_PREFIX': 'paylen',
    '_FETCH_PATH_OFF': 'paylen',
    '_FETCH_SUBJECT_OFF': 'paylen',
    '_FETCH_WINDOW_LEN': 'paylen',
    '_FETCH_WINDOW_OFF': 'paylen',
    '_FE_CLASS': 'contentprofiles',
    '_FE_CLASSES': 'contentprofiles',
    '_FE_LEVEL': 'contentprofiles',
    '_FE_NAME': 'contentprofiles',
    '_FE_NATION': 'contentprofiles',
    '_FE_NATIONS': 'contentprofiles',
    '_FE_SEX': 'contentprofiles',
    '_FE_WORLD': 'contentprofiles',
    '_FE_WORLD_NAME': 'contentprofiles',
    '_FFXI_CONTENT_CODE': 'handlelists',
    '_FFXI_IDMAP': 'handlelists',
    '_FFXI_JOB': 'contentprofiles',
    '_FFXI_JOBLEVEL': 'contentprofiles',
    '_FFXI_NATION': 'contentprofiles',
    '_FFXI_RACE': 'contentprofiles',
    '_FFXI_WORLD': 'contentprofiles',
    '_FFXI_WORLD_ID': 'handlelists',
    '_FFXI_ZONE': 'contentprofiles',
    '_FLIP_REPEAT_EVERY': 'lobbybind',
    '_FMO_COUNTRY': 'contentprofiles',
    '_FMO_FIRSTNAME': 'contentprofiles',
    '_FMO_LAST': 'contentprofiles',
    '_FMO_NAME': 'contentprofiles',
    '_FMO_ZONE': 'contentprofiles',
    '_FMO_ZONE_MAX': 'contentprofiles',
    '_FRIENDS_MOBILE_MARKER': 'handlelists',
    '_FRIEND_ACC_BODY': 'friendlist',
    '_FRIEND_ACC_SUBJECT': 'friendlist',
    '_FRIEND_GUIDMAP': 'friendlist',
    '_FRIEND_HEAL_DONE': 'lobbymail',
    '_FRIEND_HID_BITS': 'friendlist',
    '_FRIEND_HID_TAG': 'friendlist',
    '_FRIEND_PAYLEN_AT': 'paylen',
    '_FRIEND_PAYLEN_SWEEP': 'paylen',
    '_FRIEND_PUT_ASSIGNED': 'friendlist',
    '_FRIEND_PUT_FLAG_AT': 'friendput',
    '_FRIEND_PUT_GUIDS': 'friendlist',
    '_FRIEND_PUT_GUID_AT': 'friendput',
    '_FRIEND_PUT_LIVE_AT': 'friendput',
    '_FRIEND_PUT_LIVE_VAL': 'friendput',
    '_FRIEND_PUT_NAME_AT': 'friendput',
    '_FRIEND_PUT_NAME_OFFS': 'friendput',
    '_FRIEND_PUT_REC': 'friendput',
    '_FRIEND_PUT_REF_LEN': 'friendput',
    '_FRIEND_PUT_REPLY_BASE': 'paylen',
    '_FRIEND_PUT_REPLY_FIXED': 'paylen',
    '_FRIEND_PUT_SLOT_AT': 'friendput',
    '_FRIEND_PUT_STARTS': 'friendput',
    '_FRIEND_PUT_TEXT_LEN': 'friendput',
    '_FRIEND_REQ_BODY': 'friendlist',
    '_FRIEND_REQ_SUBJECT': 'friendlist',
    '_FRIEND_SLOTS': 'friendlist',
    '_FRIEND_SLOTS_LOCK': 'friendlist',
    '_FRIEND_SLOTS_TTL': 'friendlist',
    '_GROUP_CLASS_COUNT_OFF': 'friendgroups',
    '_GROUP_CLASS_ENTRY': 'friendgroups',
    '_GROUP_CLASS_ENTRY_OFF': 'friendgroups',
    '_GROUP_CLASS_GID_OFF': 'friendgroups',
    '_GROUP_CLASS_NAMES': 'friendgroups',
    '_GROUP_CREATE_F08_OFF': 'friendput',
    '_GROUP_CREATE_ID_OFF': 'friendput',
    '_GROUP_CREATE_REPLY': 'friendput',
    '_GROUP_CTL': 'handlelists',
    '_GROUP_CTL_FILE': 'handlelists',
    '_GROUP_INVITE_RE': 'resourcestore',
    '_GROUP_MEMBER_CLASS': 'friendgroups',
    '_GROUP_MEMBER_CLASS_BIT': 'friendgroups',
    '_GROUP_MEMBER_REC': 'handlelists',
    '_GROUP_MEMBER_SLOT_BIT': 'friendgroups',
    '_GROUP_MSG_NAME_OFF': 'friendgroups',
    '_GROUP_MSG_TAIL': 'friendgroups',
    '_GROUP_NAME_MAX': 'friendput',
    '_GROUP_NAME_OFF': 'friendput',
    '_GROUP_STATUS_FLAG_OFF': 'friendgroups',
    '_GROUP_STATUS_GID_OFF': 'friendgroups',
    '_HANDLEREG_APPLY': 'handlelists',
    '_HANDLEREG_SLOTS': 'handlelists',
    '_HANDLE_GUID_BITS': 'friendgroups',
    '_HANDLE_REG_MAX': 'lobbyreply',
    '_HANDLE_REG_OFF': 'lobbyreply',
    '_HANDLE_SLOTS': 'handlelists',
    '_HANDLE_STORE_N': 'lobbycapture',
    '_HANDLE_STORE_NAME': 'lobbycapture',
    '_HANDLE_STORE_REC': 'lobbycapture',
    '_HANDLE_STORE_REC_AT': 'lobbycapture',
    '_HOST_OK': 'portalauth',
    '_HTTP_METHODS': 'lobbyreply',
    '_IDREC_CONTENT_AT': 'profilerecord',
    '_IDREC_CONTENT_MAX': 'profilerecord',
    '_IDREC_CONTENT_STRIDE': 'profilerecord',
    '_LAST_FRIEND_PUT': 'lobbysearch',
    '_LAST_SEARCH': 'lobbysearch',
    '_LAST_SEARCH_COUNT': 'paylen',
    '_LAST_SEARCH_KIND': 'lobbysearch',
    '_LOBBY_DUMP': 'framing',
    '_LOBBY_DUMP_CTL': 'lobbyreply',
    '_LOBBY_DUMP_CTL_CACHE': 'lobbyreply',
    '_LOBBY_DUMP_FETCH': 'framing',
    '_LOBBY_HDR_LEN': 'framing',
    '_LOBBY_LIST': 'handlelists',
    '_LOBBY_MASK_HEAD': 'framing',
    '_LOBBY_PARTIAL_MAX': 'framing',
    '_LOBBY_PAYLEN': 'paylen',
    '_LOBBY_PAYLEN_DEFAULT': 'paylen',
    '_LOBBY_PAYLEN_UNKNOWN_SEEN': 'paylen',
    '_LOBBY_REQ_HDR_LEN': 'handlelists',
    '_LOBBY_SHAPES': 'framing',
    '_LOBBY_SHAPE_DEFAULT': 'framing',
    '_LOGIN_TRACE': 'deps',
    '_LOGIN_TRACE_MAX': 'deps',
    '_LOGOUT_GRACE_LOCK': 'presence',
    '_LOGOUT_GRACE_PENDING': 'presence',
    '_LOG_FILES': 'deps',
    '_LOG_KEEP': 'deps',
    '_LOG_LOCK': 'deps',
    '_LOG_MAX': 'deps',
    '_MAIL_ALIASES_DEFAULT': 'mailserver',
    '_MAIL_FILE_PREFIX': 'lobbymail',
    '_MAIL_IDLE': 'mailserver',
    '_MAIL_MAX_BYTES': 'mailserver',
    '_MAIL_MINTED': 'resourcestore',
    '_MAIL_MINTED_TTL': 'resourcestore',
    '_MAIL_OBJ_OFF': 'resourcestore',
    '_MAIL_PATH_PREFIX': 'lobbysearch',
    '_MAIL_PUSH_BYTE': 'lobbymail',
    '_MAIL_REPORT_BOX': 'mailserver',
    '_MAIL_STATE_CANON': 'lobbymail',
    '_MAIL_STATE_OFF': 'lobbymail',
    '_MARKER_RE': 'lobbycapture',
    '_MAX_CONNS': 'serving',
    '_MEMBER_STATUS_CACHE': 'memberstatus',
    '_MEMBER_STATUS_FILE': 'memberstatus',
    '_MEMBER_STATUS_TTL': 'memberstatus',
    '_MIN_CAPTURED_HANDLE': 'lobbycapture',
    '_MODE_ARG_FLAGS': 'ircband',
    '_MULTI_CLIENT_HOSTS': 'lobbybind',
    '_MailTrace': 'mailserver',
    '_NOHANDLER_LOG_MAX': 'lobbysearch',
    '_P0': 'authnode',
    '_PRESENCE_ACTION': 'presence',
    '_PRESENCE_B64_ALPHABET': 'presence',
    '_PRESENCE_CTL': 'presence',
    '_PRESENCE_CTL_FILE': 'presence',
    '_PRESENCE_EXT_LEN': 'presence',
    '_PRESENCE_FIELD_STATE': 'pushrecord',
    '_PRESENCE_FIRE_FILE': 'pushspool',
    '_PRESENCE_GUID_XOR': 'pushchannel',
    '_PRESENCE_STATES': 'presence',
    '_PRESENCE_TYPE': 'presence',
    '_PRESENCE_ZONE_CHATROOM': 'memberstatus',
    '_PRESENCE_ZONE_VIEWER': 'memberstatus',
    '_PROFILE_FICON': 'friendgroups',
    '_PROFILE_FIELD_VIS': 'profilerecord',
    '_PROFILE_IDREC_AT': 'profilerecord',
    '_PROFILE_IDREC_LEN': 'profilerecord',
    '_PROFILE_LEAD': 'profilerecord',
    '_PROFILE_LEVEL_DEFAULT': 'profilerecord',
    '_PROFILE_NOTIFY_AT': 'profilerecord',
    '_PROFILE_NOTIFY_LEN': 'profilerecord',
    '_PROFILE_SCHEMA': 'profilerecord',
    '_PROFILE_STEP_EXTRA': 'profilerecord',
    '_PROFILE_TRAILER_LEN': 'profilerecord',
    '_PROFILE_VIS_KEY': 'profilerecord',
    '_PROFILE_WIDTH': 'profilerecord',
    '_PUSH_CHUNK_MAX': 'pushrecord',
    '_PUSH_DEFER': 'pushspool',
    '_PUSH_DEFER_LOCK': 'pushspool',
    '_PUSH_DEFER_MAX': 'pushspool',
    '_PUSH_DEFER_WINDOW': 'pushspool',
    '_PUSH_EV_FRIEND_REQUEST': 'pushchannel',
    '_PUSH_EV_MESSAGE': 'pushchannel',
    '_PUSH_EV_PROFILE': 'pushchannel',
    '_PUSH_FIELD_CLASS': 'pushrecord',
    '_PUSH_FIELD_WIDTH': 'pushrecord',
    '_PUSH_F_BLOCK': 'pushrecord',
    '_PUSH_F_COMMENT': 'pushrecord',
    '_PUSH_F_F08': 'pushrecord',
    '_PUSH_F_ICON': 'pushrecord',
    '_PUSH_F_NAME': 'pushrecord',
    '_PUSH_F_OBJECT': 'pushrecord',
    '_PUSH_F_TAIL': 'pushrecord',
    '_PUSH_GUID_MASK': 'pushchannel',
    '_PUSH_LOCAL': 'pushspool',
    '_PUSH_SPOOL': 'pushspool',
    '_PUSH_SPOOL_IDLE': 'pushspool',
    '_PUSH_SPOOL_LOCK': 'pushspool',
    '_PUSH_SPOOL_MAX': 'pushspool',
    '_PUSH_SPOOL_OFFSET': 'pushspool',
    '_PUSH_TEXT_MAX': 'pushchannel',
    '_REJECT_WHY': 'logingate',
    '_REPORT_PATH': 'portalpages',
    '_REPORT_TAG': 'mailserver',
    '_RESOURCE_WRITE_LEN': 'resourcestore',
    '_RESOURCE_WRITE_PATHS': 'resourcestore',
    '_ROOMS_CACHE': 'lobbyrooms',
    '_ROOMS_FILE': 'lobbyrooms',
    '_ROOMS_OWNER': 'lobbyrooms',
    '_ROOMS_RESTORED': 'lobbyrooms',
    '_ROOMS_RESTORE_LOCK': 'lobbyrooms',
    '_ROOM_BOT_HOPS': 'ircband',
    '_ROOM_BOT_NICK': 'ircband',
    '_ROOM_BOT_REAL': 'ircband',
    '_ROOM_CAPACITY': 'lobbysearch',
    '_ROOM_CAPACITY_CREATED': 'lobbysearch',
    '_ROOM_LANGUAGE_NAMES': 'lobbyrooms',
    '_ROOM_MEMBERS_NAMES': 'lobbyrooms',
    '_ROOM_NAME_CACHE': 'lobbyrooms',
    '_ROOM_NAME_TTL': 'lobbyrooms',
    '_ROOM_PURPOSE_NAMES': 'lobbyrooms',
    '_ROOM_RECORD': 'lobbyrooms',
    '_ROOM_RECORD_TEMPLATE': 'lobbyrooms',
    '_ROOM_SETTING_BASES': 'lobbyrooms',
    '_ROOM_TOPIC_PREFIX': 'ircband',
    '_ROOM_TOPIC_SETTINGS_LEN': 'lobbyrooms',
    '_ROW_FIRE_FILE': 'pushspool',
    '_ROW_PUSH_DELAY': 'pushspool',
    '_ROW_PUSH_SEQ': 'pushspool',
    '_RelayDone': 'tlsrelay',
    '_S0': 'authnode',
    '_SEARCH_FIELDS': 'lobbysearch',
    '_SEARCH_ITEM_ZONE': 'lobbysearch',
    '_SEARCH_PRED': 'lobbysearch',
    '_SEARCH_QUOTE': 'lobbysearch',
    '_SEARCH_SLOTS': 'lobbysearch',
    '_SEARCH_SLOT_GLOBAL': 'lobbysearch',
    '_SEARCH_TAG': 'lobbysearch',
    '_SEARCH_TAG_ROOM': 'lobbyrooms',
    '_SEARCH_TAG_ZONE': 'lobbyrooms',
    '_SEARCH_TLV_START': 'lobbysearch',
    '_SELECT_PATH': 'paylen',
    '_SELF_GUID_PATH': 'paylen',
    '_SELF_IP': 'authcap',
    '_SESSIONS': 'lobbysession',
    '_SESSIONS_LOCK': 'lobbysession',
    '_SESSIONS_MTIME': 'lobbysession',
    '_SESSION_CONST_LE': 'framing',
    '_SESSION_FILE': 'lobbysession',
    '_SESSION_TTL': 'lobbysession',
    '_SE_REJECT_RECORD': 'logingate',
    '_SE_ROOMS': 'lobbyrooms',
    '_SHIM_LIVE_MAX': 'portalpages',
    '_SHIM_LOG_DIR': 'portalpages',
    '_SHIM_LOG_MAX': 'portalpages',
    '_SHIM_LOG_PATH': 'portalpages',
    '_SHIM_LOG_REDACT': 'portalpages',
    '_SMTP_ANGLE_RE': 'mailserver',
    '_SMTP_BARE_RE': 'mailserver',
    '_STAMPS': 'deps',
    '_STAMPS_LOCK': 'deps',
    '_STAMPS_MTIME': 'deps',
    '_STAMP_FILE': 'deps',
    '_STAMP_KEEP': 'deps',
    '_STAMP_TRY_DEFAULT': 'redirect',
    '_STAMP_TTL': 'deps',
    '_STATUS_AWAY': 'memberstatus',
    '_STATUS_CODE_AT': 'memberstatus',
    '_STATUS_INVISIBLE': 'memberstatus',
    '_STATUS_ONLINE': 'memberstatus',
    '_STATUS_ZONE_LATCH': 'memberstatus',
    '_SUBJECT_KEYED_PATHS': 'fetchpath',
    '_SUBJECT_KEYED_PREFIXES': 'fetchpath',
    '_StderrTee': 'deps',
    '_TITLES_LOADED': 'boot',
    '_TITLE_ZONE_CACHE': 'titlezone',
    '_TITLE_ZONE_FILE': 'titlezone',
    '_TITLE_ZONE_LEASE_TTL': 'titlezone',
    '_TITLE_ZONE_REFRESH': 'titlezone',
    '_TITLE_ZONE_TTL': 'titlezone',
    '_TLV_START': 'lobbyreply',
    '_TLV_TAG': 'lobbyreply',
    '_TM_AVG_RANK': 'contentprofiles',
    '_TM_CARD_LEVEL': 'contentprofiles',
    '_TM_TITLE': 'contentprofiles',
    '_UA_SERVICES': 'portalpages',
    '_ZONE_PLAYONLINE': 'lobbyrooms',
    '_ZONE_SUMMARY_RECORD': 'lobbyrooms',
    '_acct_payload': 'lobbyreply',
    '_advertise_configured': 'authcap',
    '_archive_report': 'mailserver',
    '_arm_stack_dumps': 'deps',
    '_auth_channel_loop': 'authresume',
    '_auth_session_reply': 'ircband',
    '_b64decode': 'lobbymail',
    '_b64encode': 'logingate',
    '_b64encode_exact': 'pushrecord',
    '_band_send': 'pacing',
    '_bind_corroborate_mismatch': 'lobbycapture',
    '_broadcast_presence': 'pushrecord',
    '_build_lobby_frame': 'framing',
    '_build_lobby_reply': 'lobbyreply',
    '_build_lobby_reply_pt': 'lobbyreply',
    '_build_world_reply_body': 'lobbyreply',
    '_capture_active_handle': 'lobbycapture',
    '_capture_comment': 'profilerecord',
    '_capture_fetch_subject': 'fetchpath',
    '_capture_friend_put': 'friendput',
    '_capture_group_invite': 'friendgroups',
    '_capture_one_handle': 'lobbycapture',
    '_capture_profile_write': 'profilerecord',
    '_capture_resource_write': 'resourcestore',
    '_capture_self_guid': 'fetchpath',
    '_chan_arg': 'ircband',
    '_char_display_name': 'characters',
    '_char_record': 'characters',
    '_character_names': 'characters',
    '_chr_put': 'characters',
    '_client_era': 'portalpages',
    '_client_guid_map': 'friendgroups',
    '_comment_cfg_int': 'lobbysession',
    '_comments_by_handle': 'handlelists',
    '_content_code_for_cid': 'contentprofiles',
    '_content_code_for_request': 'contentprofiles',
    '_content_game_fields': 'contentprofiles',
    '_content_profile_file': 'pfc',
    '_content_profile_note': 'pfc',
    '_content_profile_record': 'contentprofiles',
    '_content_profiles': 'pfc',
    '_content_schema_for': 'contentprofiles',
    '_created_room_list': 'lobbyrooms',
    '_created_room_zone': 'lobbyrooms',
    '_datescan_payload': 'lobbyreply',
    '_db_chars': 'handlelists',
    '_db_friends': 'friendlist',
    '_db_handles': 'handlelists',
    '_derive_lobby_reply': 'lobbyreply',
    '_do_send_friend_roster': 'friendroster',
    '_epoch': 'lobbysession',
    '_era_for_build': 'portalpages',
    '_era_for_release': 'portalpages',
    '_ext_rcpt_check': 'mailserver',
    '_ext_relay': 'mailserver',
    '_face_icons_by_handle': 'handlelists',
    '_fetch_path': 'fetchpath',
    '_fetch_subject': 'fetchpath',
    '_ffxi_char_fields': 'ffxifields',
    '_ffxi_missing_warned': 'handlelists',
    '_ffxi_world_cache': 'handlelists',
    '_ffxi_world_fields': 'ffxifields',
    '_find_session_const': 'lobbyreply',
    '_friend_addrow_presence': 'friendput',
    '_friend_addrow_push': 'friendput',
    '_friend_bitfield_mode': 'friendlist',
    '_friend_entry': 'friendlist',
    '_friend_flags_low_by_row': 'friendlist',
    '_friend_guid_probe': 'friendlist',
    '_friend_handle_slots': 'friendlist',
    '_friend_list_handle_id': 'friendlist',
    '_friend_list_record': 'friendlist',
    '_friend_load_payload': 'friendroster',
    '_friend_payload': 'friendlist',
    '_friend_push_slot_ok': 'friendroster',
    '_friend_put_apply_flags': 'friendput',
    '_friend_put_bitfield_deletes': 'friendput',
    '_friend_put_deletes': 'friendput',
    '_friend_put_flag': 'friendput',
    '_friend_put_guid': 'friendput',
    '_friend_put_name': 'friendput',
    '_friend_put_records': 'friendput',
    '_friend_put_ref': 'friendput',
    '_friend_put_renames': 'friendput',
    '_friend_put_reply': 'friendput',
    '_friend_put_reply_len': 'paylen',
    '_friend_put_row_for': 'friendput',
    '_friend_put_slot': 'friendput',
    '_friend_put_state_low': 'friendput',
    '_friend_put_text': 'friendput',
    '_friend_put_wire_ref': 'friendput',
    '_friend_request_greeting': 'lobbymail',
    '_friend_request_heal': 'lobbymail',
    '_friend_row_bitfield': 'friendlist',
    '_friend_row_handles': 'friendlist',
    '_friend_row_order': 'friendroster',
    '_friend_slot': 'friendroster',
    '_friend_slot_map_live': 'friendput',
    '_friend_slot_raw': 'friendroster',
    '_friend_slot_row': 'friendput',
    '_friend_slots_assign': 'friendlist',
    '_friend_slots_map': 'friendlist',
    '_friend_slots_publish': 'friendlist',
    '_friend_slots_update': 'friendlist',
    '_friends_cap': 'handlelists',
    '_friends_mobile_request': 'handlelists',
    '_front_is_served': 'posture',
    '_front_preamble_addr': 'authserv',
    '_front_relay_watchdog': 'posture',
    '_game_notice_line': 'gamenotice',
    '_game_notice_reply': 'gamenotice',
    '_gm_roster_nick': 'ircband',
    '_group_cfg': 'friendgroups',
    '_group_cfg_int': 'friendgroups',
    '_group_class_change': 'friendgroups',
    '_group_create': 'friendgroups',
    '_group_delete': 'friendgroups',
    '_group_join_from_message': 'friendgroups',
    '_group_member_packed': 'friendgroups',
    '_group_member_record': 'friendgroups',
    '_group_members': 'friendgroups',
    '_group_message': 'friendgroups',
    '_group_mode_push': 'friendgroups',
    '_group_my_status': 'friendgroups',
    '_group_op_nicks': 'ircband',
    '_group_record': 'friendgroups',
    '_group_role': 'friendgroups',
    '_groups_for_list': 'friendgroups',
    '_handle_list_entries': 'handlelists',
    '_handle_record': 'handlelists',
    '_handle_reg_payload': 'handlelists',
    '_handle_store_capture': 'lobbycapture',
    '_handle_store_delete': 'lobbycapture',
    '_handle_store_layout': 'lobbycapture',
    '_handle_store_records': 'lobbycapture',
    '_handle_store_text': 'lobbycapture',
    '_handlereg_payload': 'handlelists',
    '_http_request_complete': 'framing',
    '_identity_content_entries': 'contentprofiles',
    '_int_field': 'handlelists',
    '_irc_host': 'ircband',
    '_is_content_profile_request': 'contentprofiles',
    '_is_listed_chan': 'ircband',
    '_is_ps2_console': 'pacing',
    '_is_tls_hello': 'tlsrelay',
    '_kill_duplicate_logins': 'presence',
    '_list_count': 'handlelists',
    '_list_mode': 'handlelists',
    '_list_paylen': 'handlelists',
    '_list_payload': 'handlelists',
    '_live_member_status': 'memberstatus',
    '_live_rooms': 'lobbyrooms',
    '_live_title_zones': 'titlezone',
    '_load_eras': 'portalpages',
    '_lobby_arbitrate': 'lobbybind',
    '_lobby_bind': 'lobbybind',
    '_lobby_capture': 'lobbycapture',
    '_lobby_cksum': 'lobbybind',
    '_lobby_crypt': 'lobbybind',
    '_lobby_delay': 'pacing',
    '_lobby_dump_reply_n': 'lobbyreply',
    '_lobby_emit_iv': 'lobbyreply',
    '_lobby_frame_complete': 'framing',
    '_lobby_frame_pending': 'framing',
    '_lobby_handle': 'lobbyreply',
    '_lobby_header_ok': 'lobbybind',
    '_lobby_iv': 'lobbybind',
    '_lobby_iv_candidates': 'lobbybind',
    '_lobby_key': 'lobbyreply',
    '_lobby_key_for_iv': 'lobbybind',
    '_lobby_linger': 'pacing',
    '_lobby_mask': 'lobbyreply',
    '_lobby_pace_ps2': 'pacing',
    '_lobby_paylen': 'paylen',
    '_lobby_payload': 'lobbyreply',
    '_lobby_pick_iv': 'lobbybind',
    '_lobby_ps2_send': 'pacing',
    '_lobby_shape': 'lobbyreply',
    '_lobby_stamp': 'framing',
    '_lobby_try_decrypt': 'lobbyreply',
    '_lobby_until': 'framing',
    '_lobby_world_ip': 'framing',
    '_lockout_policy': 'authserv',
    '_log_auth_posture': 'posture',
    '_log_handle_locked': 'deps',
    '_logout_or_grace': 'presence',
    '_logout_wipe': 'presence',
    '_mail_address_as': 'lobbymail',
    '_mail_aliases': 'mailserver',
    '_mail_announce': 'lobbymail',
    '_mail_canon_token': 'lobbymail',
    '_mail_count': 'lobbymail',
    '_mail_db': 'mailserver',
    '_mail_drop_redundant_request': 'lobbymail',
    '_mail_is_own_echo': 'lobbymail',
    '_mail_legacy_names': 'lobbymail',
    '_mail_login_allowed': 'mailserver',
    '_mail_meta': 'lobbymail',
    '_mail_mint': 'lobbymail',
    '_mail_minted_recently': 'lobbymail',
    '_mail_name': 'lobbymail',
    '_mail_next_thread': 'lobbymail',
    '_mail_normalise': 'lobbymail',
    '_mail_note_minted': 'lobbymail',
    '_mail_notice_already_there': 'lobbymail',
    '_mail_object': 'lobbymail',
    '_mail_owner': 'lobbymail',
    '_mail_path_of': 'lobbymail',
    '_mail_paylen': 'lobbymail',
    '_mail_payload': 'lobbymail',
    '_mail_polid_member': 'mailserver',
    '_mail_push_token': 'lobbymail',
    '_mail_read_len': 'lobbymail',
    '_mail_recipient_raw_note': 'lobbymail',
    '_mail_recipient_row': 'lobbymail',
    '_mail_retire': 'lobbymail',
    '_mail_sender_slot': 'lobbymail',
    '_mail_session_allowed': 'mailserver',
    '_mail_stale_acceptance': 'lobbymail',
    '_mail_token_escape': 'lobbymail',
    '_mail_token_unescape': 'lobbymail',
    '_mailbox': 'lobbymail',
    '_mailbox_payload': 'lobbymail',
    '_marker_payload': 'lobbyreply',
    '_marker_payload_z': 'lobbyreply',
    '_member_channel_alive': 'presence',
    '_member_content_id': 'contentprofiles',
    '_member_display_name': 'handlelists',
    '_member_has_other_channel': 'presence',
    '_member_primary_handle': 'handlelists',
    '_member_status': 'memberstatus',
    '_member_status_watcher': 'pushspool',
    '_member_still_present': 'presence',
    '_mode_string': 'ircband',
    '_names_line': 'ircband',
    '_next_nonce': 'deps',
    '_nonce_counter': 'deps',
    '_note_bind': 'lobbybind',
    '_note_browse_zone': 'lobbyrooms',
    '_own_comment': 'lobbysession',
    '_parse_friend_put': 'friendput',
    '_parse_lobby_hello': 'lobbyreply',
    '_parse_mode_change': 'ircband',
    '_parse_profile_tlv': 'profilerecord',
    '_parse_report': 'mailserver',
    '_parse_room_topic': 'lobbyrooms',
    '_parse_search_tlv': 'lobbysearch',
    '_peer_build': 'pacing',
    '_peer_is_ps2': 'pacing',
    '_peer_online': 'friendlist',
    '_persistent_rooms': 'lobbyrooms',
    '_pfc_profile_reply': 'pfc',
    '_pfc_profile_subject': 'pfc',
    '_polp_version': 'patch',
    '_pop3_check_apop': 'mailserver',
    '_pop3_commit_deletes': 'mailserver',
    '_pop3_mailbox_user': 'mailserver',
    '_pop3_messages': 'mailserver',
    '_pop3_msgno': 'mailserver',
    '_portal_auth_headers': 'portalauth',
    '_portal_cache_headers': 'portalauth',
    '_portal_challenge': 'portalpages',
    '_portal_make_hello': 'portalauth',
    '_portal_md5': 'portalauth',
    '_portal_not_modified': 'portalauth',
    '_portal_roots': 'portalpages',
    '_portal_rspauth': 'portalauth',
    '_portal_validators': 'portalauth',
    '_presence_cfg': 'presence',
    '_presence_field_state': 'pushrecord',
    '_presence_fire_watcher': 'pushspool',
    '_presence_lines': 'pushrecord',
    '_presence_xxl_payload': 'presence',
    '_presence_zone': 'pushrecord',
    '_profile_identity_record': 'profilerecord',
    '_profile_notify_status': 'profilerecord',
    '_profile_record': 'profilerecord',
    '_profile_trailer_on': 'profilerecord',
    '_ps2_band_ports': 'pacing',
    '_publish_member_status': 'memberstatus',
    '_publish_rooms': 'lobbyrooms',
    '_publish_title_zone': 'titlezone',
    '_push_defer_retry': 'pushspool',
    '_push_deliver': 'pushspool',
    '_push_deliver_gmode': 'pushspool',
    '_push_deliver_grouprows': 'pushspool',
    '_push_deliver_handle': 'pushspool',
    '_push_deliver_mail': 'pushspool',
    '_push_deliver_presencerows': 'pushspool',
    '_push_deliver_rows': 'pushspool',
    '_push_deliver_watchers': 'pushspool',
    '_push_emit': 'pushspool',
    '_push_identity_guid': 'pushrecord',
    '_push_nick': 'pushrecord',
    '_push_offset_load': 'pushspool',
    '_push_offset_save': 'pushspool',
    '_push_spool_rotate': 'pushspool',
    '_push_spool_watcher': 'pushspool',
    '_rank_list_blob': 'pfc',
    '_read_for': 'authserv',
    '_read_frame': 'framing',
    '_recv_line': 'authserv',
    '_register_created_room': 'lobbyrooms',
    '_relay_tls': 'tlsrelay',
    '_relay_ucs_cgi': 'tlsrelay',
    '_release_for_build': 'portalpages',
    '_release_key': 'portalpages',
    '_release_tuple': 'portalpages',
    '_remember_iv_key': 'lobbybind',
    '_resource_blob': 'resourcestore',
    '_resource_file': 'resourcestore',
    '_resource_read_file': 'resourcestore',
    '_resource_store': 'resourcestore',
    '_resource_stored': 'resourcestore',
    '_restore_rooms_once': 'lobbyrooms',
    '_resume_fail': 'authresume',
    '_room_bot_nick': 'ircband',
    '_room_chan': 'lobbyrooms',
    '_room_list': 'lobbyrooms',
    '_room_members': 'lobbyrooms',
    '_room_of_member': 'roomregistry',
    '_room_record': 'lobbyrooms',
    '_room_roster': 'lobbyrooms',
    '_room_search_rows': 'lobbysearch',
    '_room_setting_name': 'lobbyrooms',
    '_room_topic': 'ircband',
    '_rooms_local_state': 'lobbyrooms',
    '_row_fire': 'pushspool',
    '_row_fire_watcher': 'pushspool',
    '_row_push_enabled': 'pushspool',
    '_scavenged_junk_signature': 'lobbycapture',
    '_search_calib': 'lobbysearch',
    '_search_calib_bytes': 'lobbysearch',
    '_search_calib_path': 'lobbysearch',
    '_search_cap': 'lobbysearch',
    '_search_payload': 'lobbysearch',
    '_search_result_get': 'lobbysearch',
    '_search_result_payload': 'lobbysearch',
    '_search_result_put': 'lobbysearch',
    '_search_rows': 'lobbysearch',
    '_search_slot_next': 'lobbysearch',
    '_search_tlv_items': 'lobbysearch',
    '_search_zone': 'lobbysearch',
    '_select_paylen': 'paylen',
    '_select_window': 'fetchpath',
    '_self_ip': 'authcap',
    '_send_friend_roster': 'friendroster',
    '_serve_http_on_lobby': 'lobbyserver',
    '_serve_one': 'serving',
    '_sess_dec': 'lobbysession',
    '_sess_enc': 'lobbysession',
    '_sess_member_id': 'chatsession',
    '_session_current': 'lobbysession',
    '_session_get': 'lobbysession',
    '_session_get_for': 'lobbysession',
    '_session_handle_id': 'lobbysession',
    '_session_handle_name': 'lobbysession',
    '_session_in_room': 'gamenotice',
    '_session_is_empty': 'lobbysession',
    '_session_member_id': 'lobbysession',
    '_session_put': 'lobbysession',
    '_session_record': 'lobbysession',
    '_session_sid': 'lobbysession',
    '_sessions_refresh': 'lobbysession',
    '_sessions_save_locked': 'lobbysession',
    '_shared_groups': 'pushspool',
    '_shim_live_append': 'portalpages',
    '_shim_live_sessions': 'portalpages',
    '_shim_log_store': 'portalpages',
    '_shim_tag': 'portalpages',
    '_sid_for_connection': 'lobbysession',
    '_sid_for_user_token': 'lobbysession',
    '_slots_payload': 'lobbyreply',
    '_smtp_addr': 'mailserver',
    '_smtp_deliver': 'mailserver',
    '_smtp_header': 'mailserver',
    '_smtp_is_outside': 'mailserver',
    '_smtp_sender_allowed': 'mailserver',
    '_smtp_sender_row': 'mailserver',
    '_split_lobby_messages': 'lobbyreply',
    '_stamp': 'deps',
    '_stamp_try': 'redirect',
    '_stamps_refresh': 'deps',
    '_stamps_save_locked': 'deps',
    '_status_frame_code': 'memberstatus',
    '_status_frame_zone': 'memberstatus',
    '_status_is_away': 'memberstatus',
    '_stderr_capture': 'deps',
    '_store_content_profile_write': 'profilerecord',
    '_subject_keyed': 'fetchpath',
    '_title_zone': 'titlezone',
    '_title_zone_expired': 'titlezone',
    '_title_zone_lease': 'titlezone',
    '_title_zone_watcher': 'pushspool',
    '_titles_mod': 'deps',
    '_trace': 'deps',
    '_trace_begin': 'deps',
    '_trace_done': 'deps',
    '_trace_dump': 'deps',
    '_ua_lang': 'portalpages',
    '_ua_services': 'portalpages',
    '_under': 'portalauth',
    '_unread_notice_senders': 'lobbymail',
    '_walk_profile_tlv': 'profilerecord',
    '_warn_stranded_registration': 'authserv',
    '_watcher_row_slot': 'pushspool',
    '_welcome_message': 'mailserver',
    '_who_here_flag': 'ircband',
    '_world_key': 'worldserver',
    '_xxl_class': 'ircband',
    '_xxl_gate': 'ircband',
    '_xxl_gid': 'ircband',
    '_zone_summary_record': 'lobbyrooms',
    '_zone_summary_row': 'lobbyrooms',
    'accounts': 'deps',
    'advertise_for': 'deps',
    'auth_rsa_enabled': 'authserv',
    'bind_peer': 'deps',
    'broadcast_event': 'pushspool',
    'build_field_push_record': 'pushrecord',
    'build_gate_record': 'logingate',
    'build_push_record': 'pushchannel',
    'build_redirect_token': 'deps',
    'build_session_token': 'deps',
    'contentauth': 'deps',
    'contentlist': 'deps',
    'datetime': 'deps',
    'expand_ports': 'deps',
    'extmail': 'deps',
    'field_push_lines': 'pushrecord',
    'gate_list_stamps': 'logingate',
    'gmchat': 'deps',
    'handle_authcap': 'authcap',
    'handle_authresume': 'authresume',
    'handle_authserv': 'authserv',
    'handle_directory': 'directory',
    'handle_lobby': 'lobbyserver',
    'handle_patch': 'patch',
    'handle_pop3': 'mailserver',
    'handle_smtp': 'mailserver',
    'handle_world': 'worldserver',
    'hashlib': 'deps',
    'hexdump': 'deps',
    'install_stderr_capture': 'deps',
    'issuereport': 'deps',
    'itertools': 'deps',
    'json': 'deps',
    'key_candidates': 'redirect',
    'load_config': 'deps',
    'load_login_nicks': 'redirect',
    'load_stamps': 'deps',
    'log': 'deps',
    'login_digest_salts': 'authserv',
    'main': 'main',
    'nick_client_sig': 'authserv',
    'nick_credential': 'authserv',
    'os': 'deps',
    'pmlfallback': 'deps',
    'pol_digest': 'deps',
    'pol_error_token': 'redirect',
    'pol_reject_token': 'logingate',
    'polpro': 'deps',
    'push_friend_icons': 'pushspool',
    'push_group_rosters': 'pushspool',
    'push_lines': 'pushrecord',
    'push_presence_burst': 'pushspool',
    'push_to_handle': 'pushspool',
    're': 'deps',
    'reject_line': 'logingate',
    'remember_stamp': 'deps',
    'resolve_account': 'authserv',
    'save_capture': 'deps',
    'secrets': 'deps',
    'select': 'deps',
    'serve': 'serving',
    'session_bind': 'lobbysession',
    'session_token_key': 'deps',
    'sessioncrypt': 'deps',
    'shim_build_hidden': 'deps',
    'socket': 'deps',
    'struct': 'deps',
    'sys': 'deps',
    'threading': 'deps',
    'time': 'deps',
    'titles': 'deps',
    'token_encode': 'deps',
    'yaml': 'deps',
}
_MODULES = {
    'deps': deps,
    'patch': patch,
    'redirect': redirect,
    'logingate': logingate,
    'directory': directory,
    'authcap': authcap,
    'authnode': authnode,
    'pfc': pfc,
    'presence': presence,
    'gamenotice': gamenotice,
    'chatsession': chatsession,
    'roomregistry': roomregistry,
    'friendroster': friendroster,
    'pushchannel': pushchannel,
    'pushrecord': pushrecord,
    'memberstatus': memberstatus,
    'titlezone': titlezone,
    'pushspool': pushspool,
    'ircband': ircband,
    'authserv': authserv,
    'authresume': authresume,
    'framing': framing,
    'lobbysession': lobbysession,
    'paylen': paylen,
    'fetchpath': fetchpath,
    'lobbysearch': lobbysearch,
    'friendput': friendput,
    'lobbybind': lobbybind,
    'lobbyreply': lobbyreply,
    'handlelists': handlelists,
    'friendgroups': friendgroups,
    'ffxifields': ffxifields,
    'characters': characters,
    'friendlist': friendlist,
    'lobbymail': lobbymail,
    'contentprofiles': contentprofiles,
    'profilerecord': profilerecord,
    'lobbyrooms': lobbyrooms,
    'resourcestore': resourcestore,
    'pacing': pacing,
    'lobbycapture': lobbycapture,
    'tlsrelay': tlsrelay,
    'portalauth': portalauth,
    'portalpages': portalpages,
    'lobbyserver': lobbyserver,
    'worldserver': worldserver,
    'serving': serving,
    'mailserver': mailserver,
    'posture': posture,
    'boot': boot,
    'main': main,
}


class _Facade(types.ModuleType):
    """`responders.<name>` reads and writes go to the owning core module."""

    def __getattr__(self, name):
        mod = _OWNERS.get(name)
        if mod is None:
            raise AttributeError(f"module 'responders' has no attribute {name!r}")
        return getattr(_MODULES[mod], name)

    def __setattr__(self, name, value):
        mod = _OWNERS.get(name)
        if mod is None:
            super().__setattr__(name, value)
            return
        setattr(_MODULES[mod], name, value)
        if mod == "deps":
            # an imported name (log, accounts, ...) is a copy in every module
            # that imported it; a patch has to reach each copy
            for other in _MODULES.values():
                if other is not deps and hasattr(other, name):
                    setattr(other, name, value)

    def __dir__(self):
        return sorted(set(super().__dir__()) | set(_OWNERS))


sys.modules[__name__].__class__ = _Facade

if __name__ == "__main__":
    main()
