"""Emit the client-side hosts block from config/server.yaml.

Tier-1 client setup is "static DNS": the shipped client works unmodified once
the pol.com names resolve to our server, and a hosts file is just DNS that a
user can install without running a resolver. This tool renders the block, so
the list stays derived from the server config instead of hand-copied into a
script that silently rots when a host is added.

    python tools/gen_hosts.py 203.0.113.10                 # print the block
    python tools/gen_hosts.py 203.0.113.10 -o polhosts.txt # ship it
    python tools/gen_hosts.py --names-only -o polhosts.txt # address-less list

`polhosts.txt` is what Install-PolConnect.ps1 reads; with --names-only the
installer supplies the address itself, which is the usual way to ship it (one
file, any server).
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(HERE, "..", "config", "server.yaml")

# Names the client reaches that dns.redirect_only does not list, either because
# they are only named in env.dat or only in `components`. Kept explicit so the
# reason each one is here survives.
EXTRA = [
    ("usercte.pol.com", "ucs alt hostname (components.ucs, env.dat)"),
    ("gd001.pol.com", "GM directory (components.gmd; redirect_only has gd000)"),
    ("gm001.pol.com", "GM chat (components.gmchat; redirect_only has gm000)"),
    ("info.sqex.net", "env.dat POL_SERVERINFO_PAGE_URL, second URL"),
]

# The login pool is a hardcoded pp%03d template, so the client can in principle
# ask for an index we never see. Our server answers pp000; the rest are cheap
# insurance against a session naming a different one.
POOL_EXTRA = 3


def load_hosts():
    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML required: pip install pyyaml")
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {}

    names = []
    seen = set()

    def add(name, why):
        if name not in seen:
            seen.add(name)
            names.append((name, why))

    for h in (cfg.get("dns") or {}).get("redirect_only") or []:
        add(h, "redirect_only")
    for name, why in EXTRA:
        add(name, why)
    for i in range(1, POOL_EXTRA + 1):
        add("pp%03d.pol.com" % i, "login pool spare (pp%03d template)")
    return names


def render(names, address=None):
    out = [
        "# PlayOnline private-server hosts block.",
        "# Generated by pol-server/tools/gen_hosts.py -- do not hand-edit.",
        "#",
        "# Every name the Viewer resolves, pointed at one server. This replaces",
        "# running a DNS resolver on each client machine; the client itself is",
        "# unmodified (the shipped env.dat already names these hosts).",
        "",
    ]
    width = max(len(n) for n, _ in names)
    for name, why in names:
        if address:
            out.append("%-15s %-*s  # %s" % (address, width, name, why))
        else:
            out.append("%-*s  # %s" % (width, name, why))
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("address", nargs="?",
                    help="server IPv4 the names should resolve to")
    ap.add_argument("-o", "--out")
    ap.add_argument("--names-only", action="store_true",
                    help="omit the address column (installer supplies it)")
    args = ap.parse_args(argv)

    if not args.names_only and not args.address:
        ap.error("give an address, or use --names-only")

    names = load_hosts()
    text = render(names, None if args.names_only else args.address)

    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\r\n") as f:
            f.write(text)
        print("wrote %s (%d names)" % (args.out, len(names)))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
