#!/usr/bin/env python3
"""Write the sign-up launcher into www/info.playonline.com/snews/*/index.pml.

SUPERSEDED -- refuses to run without --i-mean-it. Read this before using it.

That page is the INFORMATION page, and it is where server announcements belong;
it is now generated by tools/gen_news.py out of content/announcements.yaml.
This tool hijacked it as a plain-HTTP door into registration, back when the
real sign-up URL was unreachable: it is TLS-on-51305 with an SSLv3 ClientHello,
and our Python listener answered VERSION_TOO_LOW (client-side POL-1322).

That blocker is FIXED. The `ssl3ucs` stunnel terminator (OpenSSL built with
enable-ssl3) now answers the wizard's handshake for real -- verified end to end,
`SSLv3 ciphersuite: DES-CBC3-SHA` -- so registration is reachable the way SE
intended and the door is not needed.

Kept, rather than deleted, because pointing the client at a plain-HTTP copy of
the wizard is still the quickest way to isolate a markup problem from a
transport one. Running it costs you the Information page until you re-run
gen_news.py.

The nine locale directories are byte-identical -- the client's locale probing
tries several spellings and we do not yet know which it settles on, so all of
them get the same page. Generating rather than hand-editing keeps them that way
AND keeps the launcher's chrome identical to the wizard's, since both come out
of ucscgi's skin.

Usage:
    python gen_snews.py                      # default skin, ucs.pol.com:8080
    python gen_snews.py --action http://...  # point elsewhere
    POL_UCS_SKIN=flat python gen_snews.py    # emit the flat chrome instead
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "services"))

#: The served content tree. It lives in the SEPARATE pol-www repo (and on the
#: server, in the dataset bind-mounted at /www), so it is no longer a sibling of
#: this file. Point POL_WWW_DIR at your clone, or pass --root explicitly.
WWW_DIR = os.environ.get("POL_WWW_DIR") or os.path.join(ROOT, "www")

import ucscgi                                                # noqa: E402

#: Every spelling of the locale directory the client might ask for.
LOCALES = ["0", "1", "en", "en-US", "eu", "jp", "na", "us", "usa"]

#: The plain-HTTP twin (`ucs-plain` in docker-compose). ucs.pol.com is in
#: dns.redirect_only so it resolves to us; 8080 is the port that service
#: publishes. UNVERIFIED: the Viewer is only known to fetch PML over the band
#: ports (5130x), so whether it honours an explicit :8080 in an href is exactly
#: what the first click will tell us.
DEFAULT_ACTION = "http://ucs.pol.com:8080/pml-cgi-bin/?kinou_id=20"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--action", default=DEFAULT_ACTION,
                    help="where the Begin button points")
    ap.add_argument("--root", default=os.path.join(
        WWW_DIR, "info.playonline.com", "snews"),
        help="output dir; defaults under $POL_WWW_DIR (the pol-www clone)")
    ap.add_argument("--i-mean-it", action="store_true",
                    help="required: this overwrites the Information page")
    a = ap.parse_args()

    # SUPERSEDED -- see the module docstring. Refusing by default rather than
    # deleting the tool, because pointing the client at a plain-HTTP door is
    # still the fastest way to iterate on the wizard's markup when something
    # about the TLS path is itself under suspicion.
    if not a.i_mean_it:
        sys.exit(
            "gen_snews.py is superseded and would overwrite the Information\n"
            "page (www/info.playonline.com/snews/*/index.pml), which is now\n"
            "generated by tools/gen_news.py from content/announcements.yaml.\n"
            "\n"
            "The SSLv3 blocker this worked around is FIXED: the `ssl3ucs`\n"
            "terminator serves the real wizard over TLS on 51305, so the\n"
            "plain-HTTP door is no longer needed to reach registration.\n"
            "\n"
            "If you really want the launcher back for debugging, re-run with\n"
            "--i-mean-it, and re-run `python tools/gen_news.py` afterwards to\n"
            "put the Information page back.")

    page = ucscgi.page_launcher(a.action)
    for loc in LOCALES:
        d = os.path.join(a.root, loc)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "index.pml"), "w", encoding="utf-8") as f:
            f.write(page)
    print("wrote %d copies of the launcher (%d bytes each) under %s"
          % (len(LOCALES), len(page.encode("utf-8")), a.root))
    print("skin=%s  action=%s" % (ucscgi.SKIN["bg"], a.action))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
