#!/usr/bin/env python3
"""Print the lobby band's opcode table as Markdown, from the code that serves it.

    python tools/lobby_opcodes.py > docs/protocol/lobby-opcodes.md

One row per request opcode: the client's name for it, what the exchange is,
the reply length the server declares by default, and which functions answer
it (services/core/lobbyops.py). Opcodes that only have a length entry come
from the length table in core/paylen.py.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, "services"))

from core import lobbyops, paylen, handlelists  # noqa: E402


def fn_name(f):
    if f is None:
        return ""
    return f"`{f.__module__.split('.')[-1]}.{f.__name__}`"


def main():
    rows = {op.key: op for op in lobbyops.rows()}
    keys = sorted(set(rows) | set(paylen._LOBBY_PAYLEN) | set(handlelists._LOBBY_LIST))
    print("# Lobby band opcodes\n")
    print("Generated by `tools/lobby_opcodes.py` from `services/core/lobbyops.py`; "
          "do not edit by hand.\n")
    print("A lobby request carries its opcode in two bytes, `op1:op2`. The reply is a "
          "fixed-length record whose length the server declares first (the *length* "
          "column is the default; several opcodes compute it per request, see the "
          "*length rule* column), then the payload, then a 4-byte checksum.\n")
    print("| opcode | name | what | length | length rule | payload | capture |")
    print("|---|---|---|---|---|---|---|")
    for k in keys:
        op = rows.get(k)
        length = paylen._LOBBY_PAYLEN.get(k)
        if k in handlelists._LOBBY_LIST:
            rec, width, cap = handlelists._LOBBY_LIST[k]
            length = f"8 + count * {rec}"
        name = op.name if op else ("list" if k in handlelists._LOBBY_LIST else "")
        doc = op.doc if op else ""
        print(f"| {k[0]:d}:{k[1]:d} | {name} | {doc} | {length if length is not None else ''} | "
              f"{fn_name(op.paylen) if op else ''} | {fn_name(op.payload) if op else ''} | "
              f"{fn_name(op.capture) if op else ''} |")
    print("\nAn opcode with no row falls through to the generic rules: the length table, "
          "`POL_LOBBY_PAYLEN`, then the default with a warning that names the opcode.")


if __name__ == "__main__":
    main()
