"""Generate the build -> release-version table for every PlayOnline Viewer service.

Every POLP patch tree carries `version.dat` (or `V/version.dat` on the consoles)
in EVERY build, holding the release string SE showed the user -- `1.17.04`,
`Ver.1.05.00c`, `goodbye!`. The patch protocol only ever names the build id
(`20061212_0`), so this is the only mapping from what a client REPORTS to what a
human calls it, and it is what the portal's era rules are written against.

    python tools/viewer_builds.py --mirrors ../archive/ps2/mirrors \
                                  --out config/viewer-builds.tsv

Regenerate it whenever a bundle is re-archived. It is committed because the
server reads it at runtime and the mirrors (9.5 GB) are not in the repo.
"""
import argparse
import os
import sys


def load_tools(mirrors):
    """The bundle readers live with the mirrors, not here."""
    work = os.path.abspath(os.path.join(mirrors, ".."))
    if work not in sys.path:
        sys.path.insert(0, work)
    from slc import slc_decompress
    from polbundle import manifest
    return slc_decompress, manifest


def rows_for(mirrors, bundle, slc_decompress, manifest):
    path = os.path.join(mirrors, bundle)
    out = []
    for r in manifest(path):
        # `version.dat` at the tree root on PC, `V/version.dat` on the consoles.
        if os.path.basename(r["path"]) != "version.dat":
            continue
        blob = os.path.join(path, "blobs", r["slc"].replace("/", os.sep))
        if not os.path.isfile(blob):
            out.append((r["version"], ""))
            continue
        with open(blob, "rb") as f:
            raw = slc_decompress(f.read())
        out.append((r["version"], raw.decode("latin-1").strip()))
    return sorted(set(out))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mirrors", default="../archive/ps2/mirrors")
    ap.add_argument("--out", default="config/viewer-builds.tsv")
    a = ap.parse_args()

    slc_decompress, manifest = load_tools(a.mirrors)
    bundles = sorted(d for d in os.listdir(a.mirrors)
                     if d.endswith("-1000")
                     and os.path.isfile(os.path.join(a.mirrors, d, "patchlist.raw")))
    lines = ["# service\tbuild\trelease   (generated by tools/viewer_builds.py)"]
    total = 0
    for b in bundles:
        service = b.split("-")[0]
        for build, release in rows_for(a.mirrors, b, slc_decompress, manifest):
            lines.append(f"{service}\t{build}\t{release}")
            total += 1
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[*] {total} builds across {len(bundles)} services -> {a.out}")


if __name__ == "__main__":
    sys.exit(main())
